// =============================================================================
// apps/api/src/admin-source/payout-velocity.ts
// =============================================================================
// `P-M6-04`'s FOUR NUMBERS, AND THE CONTROL THEY MAKE IS ONE THAT PAGES A HUMAN.
//
// `INFRA:160` is one line -- "Over 2.5 times the 30 day average pages" -- and it
// is the reason nothing in this file may be approximately right. A liability
// figure that is wrong is read by an operator; a PAGER that is wrong wakes one,
// or fails to.
//
// -----------------------------------------------------------------------------
// THIS FILE TRANSCRIBES ADR-201 AND CHOOSES NOTHING
// -----------------------------------------------------------------------------
// `ADR-201` ruled the half `B2` was blocked on, and it is worth being precise
// about which half, because the blocker's own summary was wrong about it and the
// entry says so: the WINDOW was stated at `M06:95` all along, in words. What no
// document stated was WHAT THE AVERAGE AVERAGES, and without that the ratio is
// not a number.
//
// Ruling 2 settles it, and settles it BY PROOF rather than by preference. Of the
// three readings `avg_30d_cents` admits:
//
//   A. the 30-day TOTAL. The trailing 7 days are a SUBSET of the trailing 30, so
//      `last_7d <= total_30` on every possible history, so `ratio_bp <= 10000`,
//      so the alarm CAN NEVER FIRE, on any input, ever. That reading makes
//      `INFRA:160`'s pager a decoration and needs no data to refute.
//   B. the mean DAILY figure. A seven-day total is about seven times a daily
//      mean, so steady state sits near `70000 bp`, which is 2.8 times the
//      threshold: the pager fires on day one and every day after, and goes quiet
//      only on a roughly 64 percent COLLAPSE in payouts. The alarm would be
//      silent exactly when something is badly wrong.
//   C. the mean SCALED TO SEVEN DAYS. Steady state near `10000 bp`, reaching
//      `25000 bp` when a week's payouts run two and a half times normal.
//
// **B AND A ARE ELIMINATED AND C IS WHAT IS LEFT.** `FM-M6-07`'s words for the
// CUSUM transfer to A and B without a change: "Either constant alarms, which
// become noise, or none, which is the same as no chart." So the acceptance
// property for this module is NOT that it compiles. It is that the control
// DISCRIMINATES: silent in steady state, loud on a genuine excursion. A control
// that cannot be shown to be quiet under normal conditions is the defect
// `ADR-201` exists to prevent.
//
// -----------------------------------------------------------------------------
// EVERY NUMBER LIVES IN {@link PAYOUT_VELOCITY_POLICY} AND NOWHERE ELSE
// -----------------------------------------------------------------------------
// `ADR-201` ruling 8: the window "is carried in the implementation as ONE named,
// exported constant in ONE module, cited to this entry, and every reader imports
// it. Two literals at two sites is `B2` again, so the implementing session must
// not spell `7`, `30` or `25000` at a second site." Nothing below spells one.
//
// **AND `ELIGIBLE_HORIZON_TRADING_DAYS` IS NOT REUSED FOR THE NUMERATOR,
// WHICH IS THE TRAP THIS RULE LOOKS LIKE IT ASKS FOR.** `liability.ts` already
// exports a `7`. It is `EC-074`'s FORWARD horizon over accounts that will become
// eligible, and this one is `ADR-201`'s TRAILING window over money that has
// already left. Two independent quantities that happen to be equal today; a
// constant shared between them would move this pager's window the day `EC-074`
// moved its forecast, silently and with no ADR. `ADR-201` ruling 7 makes this
// number movable only by a superseding entry, and binding it to another
// document's number would delete exactly that property.
//
// -----------------------------------------------------------------------------
// THE DAY UNIT IS THE TRADING DAY AND THE MONEY IS ALL OF THE MONEY
// -----------------------------------------------------------------------------
// Ruling 3 counts both windows in TRADING DAYS over `trading_calendar`, and the
// argument is stationarity rather than the existence of a calendar: payout
// SUPPLY is generated by gates counted in trading days (minimum trading days,
// win days, the cadence gap), the snapshot's own clock is already the last
// closed day, and a calendar-day window would impose a THIRD clock on a quantity
// that has two. `M01:941` measures what that costs -- "Five trading days is 7
// calendar days in June and can be 9 to 10 across the year-end cluster" -- which
// on a RATIO of two windows means a genuine extraction surge inside the year-end
// cluster is MISSED and the first full week back PAGES on a calendar artifact.
//
// **THE CORPUS'S STRONGEST SOURCE AGAINST THAT IS `GLOSSARY:47`**, that whoever
// "reaches for the only calendar in the database reaches for a different set of
// days, and that substitution is wrong on roughly 104 days a year while looking
// exactly right in review". A payout SETTLES on the rail's clock: on Saturdays,
// on Thanksgiving, on days CME is shut. Ruling 4 is what keeps this module clear
// of that objection, and it is the reason {@link attributionDay} exists:
//
//   **Every settled payout is attributed to exactly one trading day: the first
//   trading day on or after the UTC date of its settlement.**
//
// The calendar is never asked whether a settlement HAPPENED. It is asked only
// WHICH SNAPSHOT FIRST SEES IT, which is `last closed day` semantics already in
// force on every other figure of this response. **No settlement is dropped and
// none is counted twice**, so the sum over 30 trading days is the sum over every
// settlement in the interval those days span. The window is bounded by trading
// days; the money inside it is all of the money.
//
// -----------------------------------------------------------------------------
// THE THIRTY-FIRST DAY IS READ, AND RULING 4 IS WHAT FORCES IT
// -----------------------------------------------------------------------------
// A settlement attributes to the OLDEST window day exactly when its date is at
// or before that day AND STRICTLY AFTER THE TRADING DAY BEFORE IT. Without that
// second bound every settlement in recorded history attributes to the oldest day
// of the window, because "the first trading day on or after" some date in 2019
// is, for a walk that can only see 30 days, the first day it can see.
//
// So this module asks the calendar for `30 + 1` days and uses the extra one as a
// BOUNDARY rather than as a term. It is a read fact and never an assumption, and
// the cost is that the control cannot evaluate until the estate holds 31 trading
// days inside one covered interval rather than 30. That is one extra day at
// launch, against an attribution rule that would otherwise be unfalsifiable.
//
// -----------------------------------------------------------------------------
// MONEY IS INTEGER CENTS AND THE RATIO INTRODUCES NO FLOAT
// -----------------------------------------------------------------------------
// Ruling 5 fixes the arithmetic and ruling 6 the empty denominator:
//
//   last_7d_cents  = sum over the 7 window days nearest the anchor
//   total_30_cents = sum over all 30
//   avg_30d_cents  = floor(total_30_cents * 7 / 30)
//   ratio_bp       = floor(last_7d_cents * 10000 / avg_30d_cents), or 0 when the
//                    denominator is 0
//   alarm          = ratio_bp > 25000
//
// **EVERY ONE OF THOSE IS COMPUTED IN `bigint` AND NOT IN `number`**, and the
// reason is stated rather than assumed. `amount_cents` is `bigint NOT NULL` in
// `0010` and a sum of it can exceed `2^53` before it exceeds the column; and
// `total_30_cents * 7` is formed BEFORE the division (ruling 5's own ordering, so
// the scaling loses at most 29 cents rather than compounding a per-day rounding
// thirty times), which multiplies the magnitude again. In `bigint` there is no
// step at which a value could be a float: `*` and `/` are integer operations and
// `/` TRUNCATES.
//
// **TRUNCATION IS `floor` HERE BECAUSE EVERY OPERAND IS NON-NEGATIVE, AND THAT IS
// A CHECK RATHER THAN A HOPE.** `0010` declares `amount_cents bigint NOT NULL
// CHECK (amount_cents > 0)`, so every summand is positive and every sum is at
// least zero; {@link centsOf} re-asserts the CHECK per row and
// {@link floorDivide} refuses a negative operand outright. Toward-zero and
// toward-negative-infinity agree on non-negative inputs and disagree by one
// everywhere else, so the guard is what makes ruling 5's word `floor` true of
// this code rather than nearly true.
//
// The two `floor`s round in OPPOSITE directions, which ruling 5 states rather
// than hides: flooring the DENOMINATOR makes it smaller and `ratio_bp` larger,
// erring toward alarming, which is the conservative direction for a control
// watching the firm's own money leave; flooring `ratio_bp` errs the other way by
// at most 1 bp against a threshold of 25000.
//
// -----------------------------------------------------------------------------
// WHAT THIS MODULE DOES NOT DO
// -----------------------------------------------------------------------------
// **IT DOES NOT COMPOSE `readLiability` AND IT DOES NOT WIDEN THE LIABILITY BOOK.** `liability.ts`'s `payout_velocity` stays in the `Omit`, and
// the reason is not that the numbers are unavailable -- they are, below -- but
// that this evaluator answers THREE WAYS and the wire carries ONE. `uncovered`
// and `exhausted` are `ADR-042` F-4's answers and `LiabilityResponse` has
// nowhere to put either: `ratio_bp` is a non-nullable `number` and `alarm` a
// non-nullable `boolean` (`API_CONTRACT:905`). Rendering an uncovered calendar as
// `0 / false` would be indistinguishable from a quiet week, which is `ADR-201`
// finding 3's gap arriving one field over and with a pager attached. Composing
// against a source that cannot fully serve the shape turns an honest 500 into a
// wrong answer, which is session 374's judgement on the same method.
//
// **IT WRITES NOTHING AND STORES NOTHING.** `ADR-201` ruling 7 refuses the window
// a column, on `0049`'s own reason for storing no `breaker_armed`, and refuses it
// a config value an operator sets, on `INV-M6-13`'s reason that "an 'extend'
// button is the one control-shaped affordance that would delete the control". A
// settable velocity window is that button on the alarm that watches the firm's
// own money leaving. {@link PayoutVelocityTx} carries `rows` and nothing else.
//
// -----------------------------------------------------------------------------
// THE COST, AND THE ONE UNBOUNDED TERM NAMED RATHER THAN HIDDEN
// -----------------------------------------------------------------------------
// `payout_transfers` IS READ WHOLE and it grows one row per transfer forever.
// `ADR-157` does admit a range term on the READ path, and `atLeast('settled_at')`
// would bound it -- but the term can only be minted by `packages/db`, and this
// directory holds NO import of that package, which is the property
// `LIABILITY_READ_TABLES`' own suite depends on. Taking the bound here is a
// change to this directory's port shape rather than a line in this function, so
// it is REPORTED and not taken, and the scan is measured in
// {@link PayoutVelocityCost} instead.
//
// **THE CALENDAR IS READ FIRST AND THE TRANSFERS ARE NOT READ AT ALL WHEN THE
// ANSWER CANNOT BE GIVEN.** An `uncovered` or `exhausted` calendar decides the
// verdict on its own, so paying an unbounded scan to reach it would buy a figure
// the verdict discards.
// =============================================================================

import { AdminReadError } from '../routes/admin-reads.ts';
import type { LiabilityResponse } from '../routes/admin-reads.ts';
import { readTradingLookback, TRADING_CALENDAR_TABLES } from './liability.ts';

// -----------------------------------------------------------------------------
// The port onto the database
// -----------------------------------------------------------------------------

/**
 * The tables this evaluator reads, and no others.
 *
 * THREE, AND THE THIRD IS WHAT MAKES THE OTHER TWO A WINDOW. `payoutTransfers`
 * carries the money, and the two calendar tables carry the days it is counted
 * over: `trading_calendar` says which days are sessions, `trading_calendar_loads`
 * says which days the estate has an opinion about at all, and a day outside the
 * second is UNKNOWN rather than a not-holiday (`ADR-042` F-4).
 *
 * `LIABILITY_READ_TABLES`' idiom, for its reason: a typo is a compile error here
 * and the suite asserts every member is a real `TableKey` of `packages/db`.
 */
export const PAYOUT_VELOCITY_TABLES = ['payoutTransfers', ...TRADING_CALENDAR_TABLES] as const;

/** One of {@link PAYOUT_VELOCITY_TABLES}. */
export type PayoutVelocityTable = (typeof PAYOUT_VELOCITY_TABLES)[number];

/**
 * `ADR-112`'s keyed accessor, READ HALF ONLY, over this evaluator's three tables.
 *
 * `rowsWhere` AND `rowAt` ARE ABSENT AS WELL AS THE WRITE VERBS, which is one
 * method fewer than `LiabilityTx` carries and two fewer than `FlagsTx`.
 * Every read below is a whole-table scan folded in this module, so a method this
 * evaluator cannot use is a method the next reader will use incorrectly.
 *
 * It is structurally a `TradingCalendarTx`, so {@link readTradingLookback}
 * takes this handle unchanged and the calendar is read ONCE through ONE walk.
 */
export interface PayoutVelocityTx {
  rows(key: PayoutVelocityTable): Promise<unknown[]>;
}

// -----------------------------------------------------------------------------
// The policy: ADR-201 ruling 8's one constant in one module
// -----------------------------------------------------------------------------

/**
 * A number the corpus states, with the source it was read from.
 *
 * `apps/worker/src/breaker/ports.ts`'s `PolicyNumber`, and the shape is that
 * file's rather than this one's: each value is `{state, value, cite, quote}`
 * rather than a bare number, so a reader asking "where does 25000 come from"
 * gets the answer FROM THE VALUE. `ADR-201` ruling 8's finding is that the tree
 * had already built the shape the ruling needed, and that before that entry
 * every number in a payout-velocity policy would have had to be `unstated`
 * because there was no document to cite.
 *
 * **IT IS DECLARED HERE RATHER THAN IMPORTED, AND THAT IS A REPORTED COST.**
 * `apps/worker` and `apps/api` are two deployables and neither imports the
 * other; no package in this workspace is a home for a policy vocabulary. So this
 * is a second declaration of a twelve-line type, which is `RI-18`'s subject at a
 * smaller radius, and the natural repair -- `PAYOUT_VELOCITY_POLICY` living
 * beside `LOSS_RATIO_POLICY` in `ports.ts` -- is another fence's.
 */
export type PolicyNumber =
  | {
      readonly state: 'stated';
      readonly value: number;
      readonly cite: string;
      readonly quote: string;
    }
  | {
      readonly state: 'unstated';
      readonly value: null;
      readonly cite: string;
      readonly quote: string;
    };

/**
 * What the payout-velocity alarm runs under.
 *
 * **ALL FOUR ARE `stated`, AND THAT IS EXACTLY WHAT `ADR-201` DELIVERED.**
 * `LOSS_RATIO_POLICY` ships two of five `unstated`, with a suite asserting they
 * stay that way "so filling one in is a red suite rather than a quiet commit".
 * The mirror property holds here and is asserted the same way: a member of this
 * object turning `unstated` means a citation stopped resolving, and a FIFTH
 * member appearing means a number was invented rather than transcribed.
 *
 * **THERE IS NO `metric` MEMBER AND THE ABSENCE IS DELIBERATE.**
 * `LossRatioPolicy` carries one because the breaker WRITES `plan_breaker_state.metric`
 * and one plan-day is one row. `ADR-201` ruling 7 refuses this control a column
 * of any kind, so there is no row for a metric name to key, and adding one would
 * be the first half of the column the ruling refused.
 */
export interface PayoutVelocityPolicy {
  readonly numeratorTradingDays: PolicyNumber;
  readonly denominatorTradingDays: PolicyNumber;
  readonly thresholdBp: PolicyNumber;
  readonly basisPointScale: PolicyNumber;
}

/**
 * The shipped policy. Four numbers, four citations, and none of them chosen here.
 *
 * THE THRESHOLD IS STATED BY FOUR DOCUMENTS AND ALL FOUR ARE STRICT, which is
 * why `alarm` is `>` and not `>=`. Re-derived at their sources rather than taken
 * from the entry that collected them:
 *
 *   `MERIT_BUILD_MASTER_PROMPT.md:166`  "payout velocity vs 30-day avg (alarm >2.5x)"
 *   `docs/plans/M06-admin-ops-console.md:95`  "alarming above 2.5x (constitution M6)"
 *   `docs/architecture/INFRA.md:160`  "Over 2.5 times the 30 day average pages"
 *   `research/ADVERSARY_DOSSIER.md:49`  "trips the payout-velocity alarm (>2.5x 30-day avg)"
 *
 * The fourth is `research/` and therefore descriptive rather than normative; it
 * is cited because its agreement is evidence, the number having survived being
 * restated in a document written for a different purpose. Not one of the four
 * says "at or above", so a ratio landing exactly on `25000` does not alarm.
 */
export const PAYOUT_VELOCITY_POLICY: PayoutVelocityPolicy = {
  numeratorTradingDays: {
    state: 'stated',
    value: 7,
    cite: 'ADR-201 ruling 3, M06:95 (P-M6-04)',
    quote:
      'The numerator is the 7 trading days ending at the trading day of the snapshot AS-OF, ' +
      'inclusive of that day',
  },
  denominatorTradingDays: {
    state: 'stated',
    value: 30,
    cite: 'ADR-201 ruling 2 and ruling 3, M06:95 (P-M6-04)',
    quote:
      '`avg_30d_cents` is the trailing thirty-day settled total scaled to seven days. The ' +
      'denominator is the 30 trading days ending at the same day, inclusive',
  },
  thresholdBp: {
    state: 'stated',
    value: 25000,
    cite: 'ADR-201 ruling 1; MERIT_BUILD_MASTER_PROMPT:166, M06:95, INFRA:160, ADVERSARY_DOSSIER:49',
    quote:
      '`25000` basis points, compared strictly: `alarm` is true when `ratio_bp > 25000` and ' +
      'false at exactly `25000`',
  },
  basisPointScale: {
    state: 'stated',
    value: 10000,
    cite: 'ADR-201 section 6',
    quote: 'ratio_bp = floor(last_7d_cents * 10000 / avg_30d_cents)',
  },
};

/**
 * A policy number, refused unless the corpus states it.
 *
 * `ports.ts`'s discipline made executable. An `unstated` member carries a `null`
 * and a citation to the open question, and a control that ran on one would be
 * running on a number nobody has ruled -- which is the whole of `B2`. The
 * refusal is here rather than at four call sites so a member that ever turns
 * `unstated` stops the evaluator instead of defaulting.
 */
function stated(number: PolicyNumber, name: string): bigint {
  if (number.state !== 'stated')
    throw new AdminReadError(
      `the payout-velocity policy carries \`${name}\` as UNSTATED (${number.cite}), so the alarm ` +
        'has no number to run on. ADR-201 ruling 8 makes this the one place the window lives, ' +
        'and an evaluator that supplied its own would be B2 one level down',
    );
  if (!Number.isSafeInteger(number.value) || number.value < 1)
    throw new AdminReadError(
      `the payout-velocity policy carries \`${name}\` as ${JSON.stringify(number.value)}, which ` +
        'is not a positive whole number. Money is integer cents and a threshold in basis points ' +
        'is an integer too (ADR-201 section 6)',
    );
  return BigInt(number.value);
}

// -----------------------------------------------------------------------------
// The shape of an answer
// -----------------------------------------------------------------------------

/**
 * `LiabilityResponse.payout_velocity`, INDEXED AND NEVER COPIED.
 *
 * `LiabilityBook`'s rule at one field: an index into the served type rather than
 * a hand-written shape, so a field added to the panel is a type error here on the
 * day it lands rather than a silently short object.
 */
export type PayoutVelocityPanel = NonNullable<LiabilityResponse['payout_velocity']>;

/**
 * What this evaluator can answer, and the three answers are genuinely different.
 *
 * `TradingLookback`'s shape with the money folded in, and the reason is the
 * same one: collapsing "the estate cannot say" into "here is a ratio of zero" is
 * `ADR-042` F-4's silent failure with a pager attached.
 *
 *   `evaluated`  the four wire numbers, over exactly 30 trading days
 *   `exhausted`  the calendar cannot supply the window, and it says how short
 *   `uncovered`  the estate has no opinion about the anchor day at all
 *
 * **`evaluated` IS NOT THE SAME AS `alarm: false`, WHICH IS THE DISTINCTION AN
 * OPERATOR NEEDS AND THE WIRE CANNOT CARRY.** `ADR-201` ruling 6 answers an
 * empty DENOMINATOR with `ratio_bp` 0 and `alarm` false, and finding 3 records
 * that this is indistinguishable on the wire from a quiet week. The verdict here
 * keeps the two apart for as long as the shape upstream refuses to.
 */
export type PayoutVelocityVerdict =
  | {
      readonly kind: 'evaluated';
      readonly anchor_day: string;
      readonly numerator_from_day: string;
      readonly denominator_from_day: string;
      readonly attribution_boundary_day: string;
      readonly total_30_cents: number;
      readonly panel: PayoutVelocityPanel;
    }
  | {
      readonly kind: 'exhausted';
      readonly anchor_day: string;
      readonly trading_days_found: number;
      readonly short_by: number;
      readonly detail: string;
    }
  | { readonly kind: 'uncovered'; readonly anchor_day: string | null; readonly detail: string };

/**
 * What the evaluation cost, in rows handed to this module.
 *
 * `LiabilityReadCost`'s idiom. The three attribution counters are not accounting
 * decoration: `settlementsBeforeWindow` plus `settlementsAfterAnchor` plus
 * `settlementsAttributedInWindow` is every settled transfer read, and a suite
 * that asserts the identity is asserting that ruling 4 dropped nothing.
 */
export interface PayoutVelocityCost {
  readonly transferRowsScanned: number;
  readonly settledTransfersRead: number;
  readonly settledInstantsOnUnsettledRows: number;
  readonly settlementsAttributedInWindow: number;
  readonly settlementsBeforeWindow: number;
  readonly settlementsAfterAnchor: number;
  readonly calendarRowsScanned: number;
  readonly calendarLoadsScanned: number;
  readonly coveredIntervals: number;
}

/** {@link evaluatePayoutVelocity}'s answer. */
export interface PayoutVelocityResult {
  readonly verdict: PayoutVelocityVerdict;
  readonly cost: PayoutVelocityCost;
}

// -----------------------------------------------------------------------------
// The rows, read defensively
// -----------------------------------------------------------------------------

function field(row: unknown, name: string, at: string): unknown {
  if (typeof row !== 'object' || row === null)
    throw new AdminReadError(
      `the accessor returned a ${typeof row} where ${at} was expected. A pager threshold ` +
        'evaluated over that would page an operator on a number nothing in the estate produced',
    );
  return (row as Record<string, unknown>)[name];
}

/**
 * `payout_transfers.amount_cents` as a `bigint`, WITH `0010`'s CHECK RE-ASSERTED.
 *
 * `bigint` AND NOT `number`, which is the opposite of `liability.ts`'s `cents`
 * and for a reason that only applies here. There the value is a single column
 * going straight onto the wire as a JSON integer. Here it is SUMMED over thirty
 * trading days and the sum is then MULTIPLIED BY SEVEN before a division, so the
 * magnitude the arithmetic reaches is not the magnitude the column holds.
 *
 * `CHECK (amount_cents > 0)` IS RE-ASSERTED RATHER THAN TRUSTED, and it is what
 * makes {@link floorDivide}'s truncation equal to ruling 5's `floor`. A single
 * negative amount would make one sum negative, and toward-zero and
 * toward-negative-infinity disagree by one cent exactly there.
 */
function centsOf(row: unknown, at: string): bigint {
  const value = field(row, 'amountCents', at);
  let asBig: bigint;
  if (typeof value === 'bigint') asBig = value;
  else if (typeof value === 'number' && Number.isSafeInteger(value)) asBig = BigInt(value);
  else if (typeof value === 'string' && /^-?\d+$/.test(value)) asBig = BigInt(value);
  else
    throw new AdminReadError(
      `${at} carries \`amount_cents\` as ${JSON.stringify(typeof value === 'bigint' ? value.toString() : value)}, ` +
        'which is not a whole number of cents. 0010 declares the column `bigint NOT NULL` and ' +
        'MERIT_BUILD_MASTER_PROMPT keeps money in integer cents with no float on the path',
    );
  if (asBig <= 0n)
    throw new AdminReadError(
      `${at} carries \`amount_cents\` as ${asBig.toString()}, and 0010 declares ` +
        '`CHECK (amount_cents > 0)`. A non-positive transfer is the database disagreeing with ' +
        'its own constraint, and it is the one input that would make ADR-201 ruling 5 word ' +
        '`floor` differ from the truncation this module computes',
    );
  return asBig;
}

/**
 * The UTC DATE of a settlement instant, which is the ONE place this module takes
 * one, and it is ruled rather than chosen.
 *
 * `liability.ts`'s `day()` REFUSES a timestamp on purpose, because "the exchange
 * trading day is a CT session and never a UTC calendar date". `ADR-201` ruling 4
 * asks for the other thing in terms: "the first trading day on or after THE UTC
 * DATE of its settlement". The two are consistent because they answer different
 * questions. A settlement's UTC date is not being treated as a trading day; it is
 * the input to a lookup whose OUTPUT is a trading day, and the lookup is the
 * whole of what keeps the rail's clock and the exchange's apart.
 */
function settlementDate(value: unknown, at: string): string {
  const ms =
    value instanceof Date
      ? value.getTime()
      : typeof value === 'string'
        ? Date.parse(value)
        : Number.NaN;
  if (!Number.isFinite(ms))
    throw new AdminReadError(
      `${at} carries \`settled_at\` as ${JSON.stringify(value)}, which is not an instant. ` +
        "0010's `payout_transfers_settled_has_timestamp` makes a settled transfer carry one, so " +
        'this is the transcription disagreeing with the database rather than a row to fold',
    );
  return new Date(ms).toISOString().slice(0, 10);
}

/**
 * Integer division that FLOORS, with the sign guard ruling 5 depends on.
 *
 * `bigint` `/` truncates toward zero. `ADR-201` section 6 says `floor`. The two
 * agree on non-negative operands and differ by one everywhere else, so rather
 * than write a branch nothing can reach, the non-negativity is asserted: every
 * summand is `> 0` by `0010`'s CHECK, {@link centsOf} re-asserts it per row, and
 * a negative reaching here means one of those failed.
 */
function floorDivide(numerator: bigint, denominator: bigint, at: string): bigint {
  if (numerator < 0n || denominator <= 0n)
    throw new AdminReadError(
      `${at} divided ${numerator.toString()} by ${denominator.toString()}. ADR-201 section 6 ` +
        'says `floor` and bigint division TRUNCATES, and the two agree only while both operands ' +
        'are non-negative. 0010 CHECKs `amount_cents > 0`, so this is a sum that could not have ' +
        'come from the settled transfers it claims to',
    );
  return numerator / denominator;
}

/** A `bigint` cents figure as the contract's JSON integer, or a refusal. */
function onWire(value: bigint, at: string): number {
  const asNumber = Number(value);
  if (!Number.isSafeInteger(asNumber))
    throw new AdminReadError(
      `${at} is ${value.toString()}, which is past the safe integer range. API_CONTRACT section ` +
        '1 types every `_cents` member a JSON integer, and a rounded one is wrong where it is ' +
        'hardest to notice',
    );
  return asNumber;
}

// -----------------------------------------------------------------------------
// Attribution, which is ruling 4
// -----------------------------------------------------------------------------

/**
 * The first window day at or after a settlement date, or which side it fell.
 *
 * THE WINDOW DAYS ARE CONSECUTIVE TRADING DAYS AND THAT IS WHAT MAKES A SCAN
 * CORRECT. {@link readTradingLookback} takes every non-holiday row inside one
 * covered interval and slices the newest `span`, so no session is skipped
 * between two neighbours: the first entry at or after a date IS the first
 * trading day at or after it, with no third table consulted.
 *
 * `boundary` IS THE TRADING DAY BEFORE THE WINDOW and it is the whole reason a
 * settlement from 2019 does not land on the window's oldest day. A date at or
 * before it attributed to a day this walk cannot see.
 */
function attributionDay(
  date: string,
  boundary: string,
  windowDays: readonly string[],
  anchorDay: string,
): { readonly where: 'before' } | { readonly where: 'after' } | { readonly day: string } {
  if (date > anchorDay) return { where: 'after' };
  if (date <= boundary) return { where: 'before' };
  for (const day of windowDays) if (day >= date) return { day };
  // UNREACHABLE, AND IT IS ASSERTED RATHER THAN ASSUMED. `date <= anchorDay` and
  // the anchor is the last window day, so the loop above always returns. A throw
  // here would mean the window came back without its own anchor in it.
  throw new AdminReadError(
    `a settlement dated ${date} is at or before the anchor ${anchorDay} and after the boundary ` +
      `${boundary}, and no day of the window is at or after it. The window is ` +
      `${String(windowDays.length)} consecutive trading days ending at the anchor, so this is ` +
      'the walk returning a window that does not contain its own anchor',
  );
}

// -----------------------------------------------------------------------------
// The evaluation
// -----------------------------------------------------------------------------

/**
 * `P-M6-04`'s four numbers as of an instant, or the reason there are none.
 *
 * `ADR-201` rulings 1 through 6 transcribed, and every number taken from
 * {@link PAYOUT_VELOCITY_POLICY} rather than spelled here (ruling 8).
 *
 * THE ORDER OF THE TWO READS IS PART OF THE DESIGN. The calendar decides whether
 * a verdict is possible at all, and `payout_transfers` is the unbounded scan, so
 * an `uncovered` or `exhausted` calendar returns before a single transfer row is
 * read and says so in {@link PayoutVelocityCost} with a `transferRowsScanned` of
 * zero.
 */
export async function evaluatePayoutVelocity(
  tx: PayoutVelocityTx,
  asOf: string,
): Promise<PayoutVelocityResult> {
  const numeratorDays = stated(PAYOUT_VELOCITY_POLICY.numeratorTradingDays, 'numeratorTradingDays');
  const denominatorDays = stated(
    PAYOUT_VELOCITY_POLICY.denominatorTradingDays,
    'denominatorTradingDays',
  );
  const thresholdBp = stated(PAYOUT_VELOCITY_POLICY.thresholdBp, 'thresholdBp');
  const bpScale = stated(PAYOUT_VELOCITY_POLICY.basisPointScale, 'basisPointScale');

  if (numeratorDays > denominatorDays)
    throw new AdminReadError(
      `the payout-velocity policy makes the numerator window ${numeratorDays.toString()} trading ` +
        `days and the denominator ${denominatorDays.toString()}. ADR-201 ruling 2's proof that ` +
        'the 30-day TOTAL cannot be the reading rests on the numerator window being a SUBSET of ' +
        'the denominator window, and a numerator longer than its own denominator is not one',
    );

  // THE THIRTY-FIRST DAY IS THE ATTRIBUTION BOUNDARY AND NOT A TERM OF THE
  // WINDOW. The header states why ruling 4 forces it to be read rather than
  // assumed.
  const span = Number(denominatorDays) + 1;
  const { lookback, cost: calendarCost } = await readTradingLookback(tx, asOf, span);

  const emptyTransferCost = {
    transferRowsScanned: 0,
    settledTransfersRead: 0,
    settledInstantsOnUnsettledRows: 0,
    settlementsAttributedInWindow: 0,
    settlementsBeforeWindow: 0,
    settlementsAfterAnchor: 0,
    ...calendarCost,
  } as const;

  if (lookback.kind === 'uncovered')
    return {
      verdict: { kind: 'uncovered', anchor_day: lookback.anchor_day, detail: lookback.detail },
      cost: emptyTransferCost,
    };

  if (lookback.kind === 'exhausted')
    return {
      verdict: {
        kind: 'exhausted',
        anchor_day: lookback.anchor_day,
        trading_days_found: lookback.days.length,
        short_by: lookback.short_by,
        detail:
          `${lookback.detail}. ADR-201 section 7 answers an EMPTY DENOMINATOR and cannot answer ` +
          'an ABSENT WINDOW: a thirty-day total scaled by 7/30 when the calendar held fewer than ' +
          'thirty days is a denominator smaller than the one four documents describe, and a ' +
          'smaller denominator is a larger ratio against a threshold that pages',
      },
      cost: emptyTransferCost,
    };

  const walked = lookback.days.map((entry) => entry.trading_day);
  const boundaryDay = walked[0];
  const windowDays = walked.slice(1);
  const anchorDay = lookback.anchor_day;
  if (boundaryDay === undefined || windowDays.length !== Number(denominatorDays))
    throw new AdminReadError(
      `the trailing walk resolved ${String(walked.length)} trading days where ` +
        `${String(span)} were asked for. A resolved lookback returns exactly its span, so this ` +
        'is the walk disagreeing with its own verdict',
    );

  const numeratorFromDay = windowDays[windowDays.length - Number(numeratorDays)];
  const denominatorFromDay = windowDays[0];
  if (numeratorFromDay === undefined || denominatorFromDay === undefined)
    throw new AdminReadError(
      'the trailing walk resolved a window with no first day, which a window of ' +
        `${String(denominatorDays)} consecutive trading days cannot be`,
    );

  // THE UNBOUNDED SCAN, PAID ONLY NOW THAT A VERDICT IS POSSIBLE.
  const transferRows = await tx.rows('payoutTransfers');

  const attributed = new Map<string, bigint>();
  for (const day of windowDays) attributed.set(day, 0n);

  let settledTransfersRead = 0;
  let settledInstantsOnUnsettledRows = 0;
  let inWindow = 0;
  let before = 0;
  let after = 0;

  for (const row of transferRows) {
    const at = 'a payout transfer row';
    const status = field(row, 'status', at);
    if (typeof status !== 'string' || status === '')
      throw new AdminReadError(
        `${at} carries no \`status\`, and 0010 declares the column \`text NOT NULL\` with a ` +
          'CHECK over five rail states. A transfer whose state is unreadable is money this ' +
          'evaluator can neither count nor safely ignore',
      );

    const settledAt = field(row, 'settledAt', at);
    const hasInstant = settledAt !== null && settledAt !== undefined;

    // **THE `CHECK` IS ONE-DIRECTIONAL AND THE SELECTION IS ON `status`.**
    // `payout_transfers_settled_has_timestamp` is
    // `CHECK (status <> 'settled' OR settled_at IS NOT NULL)`, which forbids a
    // settled row with no instant and PERMITS a failed or retrying row that
    // carries one. So selecting on `settled_at IS NOT NULL` would count a
    // transfer the rail did not settle as money that left, which overstates the
    // numerator of an alarm. Selecting on `status` is safe in the other
    // direction because the CHECK guarantees the instant is there.
    if (status !== 'settled') {
      if (hasInstant) settledInstantsOnUnsettledRows += 1;
      continue;
    }
    if (!hasInstant)
      throw new AdminReadError(
        `${at} carries \`status = 'settled'\` and no \`settled_at\`, which ` +
          "0010's `payout_transfers_settled_has_timestamp` forbids outright. That is the " +
          'database disagreeing with its own CHECK rather than a row to attribute',
      );

    settledTransfersRead += 1;
    const date = settlementDate(settledAt, at);
    const cents = centsOf(row, at);
    const landed = attributionDay(date, boundaryDay, windowDays, anchorDay);
    if ('where' in landed) {
      if (landed.where === 'before') before += 1;
      else after += 1;
      continue;
    }
    inWindow += 1;
    attributed.set(landed.day, (attributed.get(landed.day) ?? 0n) + cents);
  }

  let total30 = 0n;
  let last7 = 0n;
  for (const day of windowDays) {
    const cents = attributed.get(day) ?? 0n;
    total30 += cents;
    if (day >= numeratorFromDay) last7 += cents;
  }

  // RULING 5, IN THE ORDER IT WRITES IT. `total_30_cents * 7` is formed before
  // the division, so the scaling loses at most 29 cents rather than compounding a
  // per-day rounding thirty times.
  const avg30 = floorDivide(total30 * numeratorDays, denominatorDays, 'avg_30d_cents');

  // RULING 6. A velocity alarm is a RELATIVE control and a firm with no payout
  // history has nothing to be relative to; firing on an empty denominator is
  // `AS-M6-02`'s self-inflicted outage with a pager instead of a sales pause.
  const ratioBp = avg30 === 0n ? 0n : floorDivide(last7 * bpScale, avg30, 'ratio_bp');

  return {
    verdict: {
      kind: 'evaluated',
      anchor_day: anchorDay,
      numerator_from_day: numeratorFromDay,
      denominator_from_day: denominatorFromDay,
      attribution_boundary_day: boundaryDay,
      total_30_cents: onWire(total30, 'the trailing 30 trading day settled total'),
      panel: {
        last_7d_cents: onWire(last7, 'last_7d_cents'),
        avg_30d_cents: onWire(avg30, 'avg_30d_cents'),
        ratio_bp: onWire(ratioBp, 'ratio_bp'),
        // RULING 1, STRICT. Four documents say "above", "over" or ">", and not
        // one says "at or above", so exactly 25000 does not page.
        alarm: ratioBp > thresholdBp,
      },
    },
    cost: {
      transferRowsScanned: transferRows.length,
      settledTransfersRead,
      settledInstantsOnUnsettledRows,
      settlementsAttributedInWindow: inWindow,
      settlementsBeforeWindow: before,
      settlementsAfterAnchor: after,
      ...calendarCost,
    },
  };
}
