import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { expect, test } from 'vitest';

import { canonicalInput, CANONICAL_POPULATION_SPEC, CANONICAL_SEED } from './canonical.ts';
import { renderRun } from '../src/simulator/emit.ts';
import { buildPopulation } from '../src/simulator/population.ts';
import { simulate } from '../src/simulator/session.ts';

// CI-02, the `unit` project.
//
// =============================================================================
// DETERMINISM IS THE WHOLE VALUE. SAME SEED, BYTE-IDENTICAL OUTPUT.
// =============================================================================
// A simulator that drifts run to run cannot be the thing goldens are derived
// against: every fixture built on it would move for a reason that has nothing
// to do with the scenario, and the first response to a red fixture would be to
// regenerate it, which is TR-03 with the safety off.
//
// Four assertions, and each catches something the others cannot.
//
//   1. TWO RENDERS IN ONE PROCESS agree. Catches a clock read, a `Math.random`,
//      an iteration over an unordered structure.
//   2. THE COMMITTED BYTES still match. Catches everything the first cannot: a
//      change to a draw, a column, a rounding, an ordering, ACROSS RUNS AND
//      ACROSS SESSIONS. This is the assertion the other three exist to support.
//   3. A DIFFERENT SEED produces different bytes. Without it, an emitter that
//      ignored its seed entirely would pass the first two.
//   4. THE POPULATION SIZE does not move an account's rows. This is the
//      property `rng.ts` keys its draws for, and it is what lets a scenario add
//      an account without invalidating every fixture derived against the run.
//
// -----------------------------------------------------------------------------
// WHAT THE COMMITTED BYTES ARE, AND WHAT THEY ARE NOT
// -----------------------------------------------------------------------------
// THEY ARE NOT A `GS-nnn` GOLDEN FILE AND MUST NEVER BE TREATED AS ONE. TR-01
// is that a golden file's expected value is computed BY HAND FROM THE PROSE by
// somebody reading the prose rather than the code; these bytes are generated by
// the emitter and prove only that the emitter has not changed. They live in
// this package rather than in `packages/rules-engine/fixtures`, and this file
// is `.test.ts` rather than `.golden.test.ts` so it lands in CI-02's `unit`
// project and never in CI-03, whose whole subject is the engine's fixtures.
//
// The correctness assertions are elsewhere and are structural:
// `session.test.ts` checks the identities the schema declares, `csv.test.ts`
// checks the rendering, and the conformance suite M02 section 8.2 specifies is
// what the vendor call is run against.
//
// REGENERATION IS DELIBERATE AND VISIBLE:
//
//     MERIT_UPDATE_CANONICAL=1 pnpm vitest run --project unit packages/rithmic
//
// and the diff it produces is the record of what moved. A run that regenerates
// reports it and FAILS, so a regeneration can never be mistaken for a pass.
// =============================================================================

const HERE = dirname(fileURLToPath(import.meta.url));
const CANONICAL_DIR = join(HERE, 'fixtures', 'canonical');
const UPDATING = process.env['MERIT_UPDATE_CANONICAL'] === '1';

test('the same seed renders byte-identical files twice in one process', () => {
  const first = renderRun(simulate(canonicalInput()));
  const second = renderRun(simulate(canonicalInput()));
  expect(second.map((file) => file.sha256Hex)).toEqual(first.map((file) => file.sha256Hex));
  for (const [index, file] of first.entries()) {
    expect(second[index]?.bytes).toEqual(file.bytes);
  }
});

test('the canonical run still renders the committed bytes', () => {
  const files = renderRun(simulate(canonicalInput()));
  expect(files.length).toBeGreaterThan(0);

  if (UPDATING) {
    mkdirSync(CANONICAL_DIR, { recursive: true });
    for (const file of files) writeFileSync(join(CANONICAL_DIR, file.fileName), file.bytes);
    throw new Error(
      `MERIT_UPDATE_CANONICAL=1 rewrote ${files.length} canonical files. This run FAILS on ` +
        'purpose: a regeneration is a diff to read, never a passing test. Re-run without the ' +
        'variable to check the bytes that were just written.',
    );
  }

  for (const file of files) {
    const path = join(CANONICAL_DIR, file.fileName);
    // A missing fixture is a failure and not a skip. `repo-invariants.mjs`
    // states the rule this borrows: a check that cannot run is not a check that
    // passed.
    expect(existsSync(path), `${file.fileName} is missing from test/fixtures/canonical`).toBe(true);
    expect(new Uint8Array(readFileSync(path)), `${file.fileName} drifted`).toEqual(file.bytes);
  }
});

test('a different seed produces different bytes', () => {
  // The counter-assertion. An emitter that ignored its seed would satisfy every
  // other test in this file.
  const input = canonicalInput();
  const other = simulate({
    ...input,
    seed: `${CANONICAL_SEED}-variant`,
    population: buildPopulation(
      { ...CANONICAL_POPULATION_SPEC, seed: `${CANONICAL_SEED}-variant` },
      2,
    ),
  });
  const baseline = renderRun(simulate(input)).map((file) => file.sha256Hex);
  const variant = renderRun(other).map((file) => file.sha256Hex);
  expect(variant).not.toEqual(baseline);
});

test('growing the population does not move an existing account', () => {
  // The property keyed draws buy, asserted directly. Account i is a pure
  // function of (seed, i), so the first eight accounts of a population of
  // twenty are the first eight of a population of eight, day for day and cell
  // for cell.
  const small = simulate(canonicalInput());
  const large = simulate({
    ...canonicalInput(),
    population: buildPopulation({ ...CANONICAL_POPULATION_SPEC, accountCount: 20 }, 2),
  });

  expect(large.population.length).toBeGreaterThan(small.population.length);
  for (const [index, account] of small.population.entries()) {
    expect(large.population[index]).toEqual(account);
  }

  for (const [sessionIndex, session] of small.days.entries()) {
    const grown = large.days[sessionIndex];
    expect(grown).toBeDefined();
    for (const [accountIndex, day] of session.entries()) {
      expect(grown?.[accountIndex]).toEqual(day);
    }
  }
});

test('the emitted rows for an existing account are identical in the larger run', () => {
  // The same property at the FILE level rather than the model level, because
  // the two could diverge: an emitter that sorted its rows by a value rather
  // than by population order would pass the test above and fail this one.
  const rowsFor = (accountCount: number): string[] =>
    renderRun(
      simulate({
        ...canonicalInput(),
        population: buildPopulation({ ...CANONICAL_POPULATION_SPEC, accountCount }, 2),
      }),
      { kinds: ['eod_report'] },
    )
      .flatMap((file) => file.contents.split('\n'))
      .filter((line) => line.startsWith('SIMACC'));

  const small = rowsFor(8);
  const large = rowsFor(20);
  expect(small.length).toBeGreaterThan(0);
  for (const row of small) expect(large).toContain(row);
});
